### ISSUE TITLE
Catacombs generating lag

### ISSUE THREAD

**Issue by XBlackLeopardX** [NightKosh/GraveStone-mod#159]
I've noticed that catacombs tend to generate a lot of FPS lag when you are near them in my modpack im wondering if its from all the graves being rendered? im running this on my server FYI
if there is a certain log you would like to look at or something just tell me which
I am using the latest of everything

**Comment by XBlackLeopardX** [comment]
yeah running it even now without changing any settings in the config i go down to 5-10 FPS when i come close or in the catacombs

**Comment by XBlackLeopardX** [comment]
I disabled a bunch of the graves and stuff from spawning in the config so you done have the extra graves all around along with the catacombs graveyard so im wondering if it may be the bone piles that cause the fps drop?

**Comment by NightKosh** [comment]
- [ ] Config to disable "pile of bones" generation
- [ ] Check day time only at mob spawn
- [ ] Create special object to handle day time and some time events for all world instead of doing it for every grave.
- [ ] Check is player in range only at mob spawn
- [ ] Get a new mob at mob spawn (already done, do not break it!)
- [ ] Check nearby mobs amount only at mob spawn (already done, do not break it!)
- [ ] Create a special object for catacombs graves to handle spawn logic in it for group of graves(for all graves in room) instead of doing it for every grave

**Comment by NightKosh** [comment]
A lot of tests required!!!

**Comment by NightKosh** [comment]
It's really improve performance!
30-50 fps on previouse verion VS >59 fps on new.
